plugins {
    id "net.fabricmc.fabric-loom-remap" version "${loom_version}"
    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        url = "https://cursemaven.com/"
        content { includeGroup "curse.maven" }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modImplementation "curse.maven:patchouli-fabric-edition-1664943:${project.patchouli_file}"
    include modApi("teamreborn:energy:${project.energy_api_version}")

    testImplementation platform("org.junit:junit-bom:5.12.1")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.named("jar", Jar).configure {
    from("LICENSE")
}

tasks.named("sourcesJar", Jar).configure {
    from("LICENSE")
}

test {
    useJUnitPlatform()
    maxHeapSize = "512m"
    maxParallelForks = 1
    systemProperty "fabric.development", "true"
    doFirst {
        systemProperty "fabric.addMods", configurations.testRuntimeClasspath.asPath
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    repositories {
    }
}
