org.gradle.jvmargs=-Xmx1536M
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=false
org.gradle.configuration-cache=false

minecraft_version=1.21.1
loader_version=0.19.1
loom_version=1.14.10
fabric_api_version=0.116.11+1.21.1
patchouli_version=1.21.1-93-FABRIC
energy_api_version=4.1.0

mod_version=0.2.1+1.21.1
maven_group=io.github.millrace.auracascade
archives_base_name=aura-cascade
